$('.carousel-1').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    responsive:{
        0:{
            items:1
        },    
        768:{
            items:2
        },
        920:{
            items:3
        },
        1300:{
            items:4
        }
    }
})

$('.owl-two').owlCarousel({
    loop:true,
    margin:30,
    nav:true,
    responsive:{
        0:{
            items:1
        },    
        620:{
            items:2
        },
        920:{
            items:3
        }
    }
})